CLASS zma0_cl_sfut_deere_bhv DEFINITION PUBLIC ABSTRACT FINAL
    FOR BEHAVIOR OF zma0_ce_deere.

  PUBLIC SECTION.

  PROTECTED SECTION.

  PRIVATE SECTION.

ENDCLASS.



CLASS ZMA0_CL_SFUT_DEERE_BHV IMPLEMENTATION.
ENDCLASS.
